### ISSUE TITLE
Can not run any commands

### ISSUE THREAD

**Issue by tecbeast42** [TheColorRed/vscode-laravel-artisan#33]
Hi i am using linux and the extension does not work at all for me.

I get the following errors
```
[CMD] "/usr/bin/php" artisan cache:clear  
[ERR] Command failed: cd "/home/tecbeast/Code/path/to/project/" && "/usr/bin/php" artisan cache:clear
```

Running /usr/bin/php -v

```
PHP 7.2.11 (cli) (built: Oct  9 2018 18:14:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

am i missing something here?

**Comment by tecbeast42** [comment]
okay i found the problem. We load env vars not from `.env` but through docker the extension assumes all default values which puts the project into production and it breaks because dusk is installed and loaded. 

I am not really sure what to do here. Maybe it is possible to make it more docker friendly. 

I might be able to run it if there were no `"` around the php command. 
e.g. 

> docker run --rm laravel php

**Comment by TheColorRed** [comment]
I am not familiar with docker, so I am not sure if this fix will work with docker projects or not, but I have added a config setting, `artisan.docker.enabled` (if you have a better setting name please let me know). This setting is best set within the project instead of globally.

So, in your `.vscode/settings.json` set `artisan.docker.enabled: true`, and it should then run the command:

    docker run --rm "${cmd.replace(/"/g, '\"')}"

Please give this a try and let me know. Thanks!

[laravel-artisan-0.0.24.vsix.zip](https://github.com/TheColorRed/vscode-laravel-artisan/files/2516066/laravel-artisan-0.0.24.vsix.zip)

**Comment by robsontenorio** [comment]
@TheColorRed This does not work, because some people use docker-compose. Instead of run a hardcoded command as you suggested, just let user place the custom command.
```
artisan.docker.enabled:  true
artisan.docker.command: <full command with path> 
```

Can you release a new patch?

**Comment by robsontenorio** [comment]
@TheColorRed Just sent a PR ;)
